### ISSUE TITLE
group cards section

### ISSUE THREAD

**Issue by MadhushaPrasad** [sliit-foss/student-sorter-fn#3]
assign: @AshenWijesingha

**Comment by SahasR** [comment]
Closes: https://github.com/sliit-foss/subcommittee/issues/4

**Comment by MadhushaPrasad** [comment]
@miyurugunarathna is this one in progress?

**Comment by miyurugunarathna** [comment]
No. Design is not finalized yet.

**Comment by MadhushaPrasad** [comment]
@miyurugunarathna can we close this issue? is it done?
