### ISSUE TITLE
Create a project for this repo

### ISSUE THREAD

**Issue by MadhushaPrasad** [sliit-foss/student-sorter-fn#5]

**Comment by MadhushaPrasad** [comment]
@Shehanka

**Comment by Shehanka** [comment]
@MadhushaPrasad what do you mean by project GH Board?

**Comment by MadhushaPrasad** [comment]
![IMG_20220105_211524](https://user-images.githubusercontent.com/50085447/148246418-a8c41ac9-2998-43ad-938f-73b0af19024c.jpg)
This one,now thats ok👍
